### ISSUE TITLE
Game Crashing from Repairman Enchantment

### ISSUE THREAD

**Issue by MiningPuff** [MrCrayfish/Backpacked#88]
I recently enchanted the backpack with Repairman, and after putting a tool in with mending is it the game would crash upon collecting the EXP. I am playing the Better Minecraft [FORGE] - 1.18.1 v19, and here is the crash report.

[crash-2022-03-13_21.46.25-server.txt](https://github.com/MrCrayfish/Backpacked/files/8241808/crash-2022-03-13_21.46.25-server.txt)

I am unable to get back into the game due to it crashing again when I reenter the world. Has anyone have something similar happen, or know how to fix the issues. Thank you.

**UPDATE**
I somehow powered through upon entering my world by moving away from the EXP orbs as the world was loading. I later backed up my save file and tried to recreate the same scenario under different conditions without the game crashing again. 

When the game did crash, it was in my zombie EXP Farm I had made and I gain a lot of EXP from the mass mobs. I think it maybe due to the large quantity of EXP orbs I absorb at once causing the crash.

**Comment by Jeramy-T** [comment]
I just had the same issue on Better Minecraft [FORGE] - 1.18.1 v20 (Backpacked 2.1.1)

When I would connect the following would happen:

net.minecraft.ReportedException: Ticking player at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at java.lang.Thread.run(Thread.java:833) [?:?] Caused by: java.lang.StackOverflowError at net.minecraft.nbt.CompoundTag.m_128435_(CompoundTag.java:237) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.nbt.CompoundTag.m_128425_(CompoundTag.java:246) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.nbt.CompoundTag.m_128461_(CompoundTag.java:324) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.world.item.enchantment.EnchantmentHelper.m_44843_(EnchantmentHelper.java:71) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.world.item.enchantment.EnchantmentHelper.m_182446_(EnchantmentHelper.java:54) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?] at net.minecraft.world.item.enchantment.EnchantmentHelper.m_44839_(EnchantmentHelper.java:290) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]

Then, the server console gets spammed with "at net.minecraft.world.entity.ExperienceOrb.m_147092_(ExperienceOrb.java:226) ~[server-1.18.1-20211210.034407-srg.jar%23204!/:?]"  and I eventually lose connection.

My only work around is to kill the offending player through the server console to enable access.

**Comment by Jeramy-T** [comment]
Updated server/client to 1.18.1 v2.1.2 and issue remained.

**Comment by MrCrayfish** [comment]
The patch is not out yet.
