### ISSUE TITLE
your just lazy dont close until fixed

### ISSUE THREAD

**Issue by VovelPunch** [MrCrayfish/Backpacked#99]
Mohist
lightfall like bungeecord but for mods
issue:
cant connect to server.
[latest.log](https://github.com/MrCrayfish/Backpacked/files/8355093/latest.log)

blaming other good services for your mistakes is wrong. And I will nolonger support you if you close this issue again. I though crayfish
stood for something good and not something lazy as fuck!

**Comment by MrCrayfish** [comment]
This is a lightfall issue, not my mod. The stacktrace in the crash report is related to code contained within lightfall. I told you in the first issue that it's not my mod, their software just doesn't support the features of the game correctly. I willl point out the issue is related to command argument types which their software should be able to support correctly.

And yes, I am blaming their software and previous forks of bungeecord that implement Forge support. It's been an constant issue that developers get sent crash logs for something not related to their mods. I hope the developers do find a solution since people benefit from the software but it's not my problem to solve.
